table dMarcas
	lineageTag: 55a6f41d-f2c1-46c6-822e-37d341173da0

	column Código_Marca
		dataType: int64
		formatString: 0
		lineageTag: 4b5f60c1-d9c1-4624-b725-dc7f66507b28
		summarizeBy: none
		sourceColumn: Código_Marca

		annotation SummarizationSetBy = Automatic

	column Marca
		dataType: string
		lineageTag: b0e1eb14-c0fa-4435-9acd-f932c95ac81d
		summarizeBy: none
		sourceColumn: Marca

		annotation SummarizationSetBy = Automatic

	column Origem
		dataType: string
		lineageTag: b3b2d9c0-ea24-409a-ad27-15011626d959
		summarizeBy: none
		sourceColumn: Origem

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		lineageTag: 0d9f8126-47f5-4d76-b89f-ee5c2a56a2af
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	partition dMarcas = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/Ricardo-Filgueiras/Projeto-Opuline-AnaliseDados/refs/heads/main/basedados/dados/Marcas.csv"),[Delimiter=";", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Código_Marca", Int64.Type}, {"Marca", type text}, {"Origem", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

